### ISSUE TITLE
Compilation with oF v0.9

### ISSUE THREAD

**Issue by chankalun** [asarasua/ofxKinectFeatures#1]
Hello, may I ask if there is an update version to compile with oF v0.9 available please?

Cheers,
Karen

**Comment by asarasua** [comment]
Thanks for pointing this out.

It's just a matter of project configuration, so I'll commit a 0.9-compatible version during the day.

Cheers

**Comment by chankalun** [comment]
Thanks a lot! x

**Comment by chankalun** [comment]
Hello, I have an error of "Cannot initialise return object of type 'ofxMocapElement _' with an rvalue of type 'bool'" in `ofxMocapElement_ ofxKinectFeatures::getElement(int _id){}` on oF v0.9.2, may I ask if that is because it is not compatible with this latest oF version please? Cheers!

**Comment by chankalun** [comment]
Hello, sorry to bug you again but I would like to ask if the 0.9-compatible version will be out soon please?
Cheers,
Karen

**Comment by asarasua** [comment]
ofxKinectFeatures itself is 0.9-compatible. ofxOpenNI (with which the examples in Mac are done) is not. I'm pretty busy with other stuff to make these new examples for Mac, but using any 0.9-compatible library to handle the skeleton data should do the trick.

**Comment by asarasua** [comment]
P.S:

If you don't know how to use an alternative for ofxOpenNI and need to start from one of the provided examples, the most immediate solution is to use some [older OF version](http://openframeworks.cc/download/older/).
