### ISSUE TITLE
crash when loading joints in multiple ofxkinectFeatures

### ISSUE THREAD

**Issue by danaavesar** [asarasua/ofxKinectFeatures#4]
I have declared a map in my header file where keys correspond to userIds
 map<int,ofxKinectFeatures> featExtractors;
Then I set it up in the update loop:
<img width="651" alt="screen shot 2016-05-02 at 5 12 30 pm" src="https://cloud.githubusercontent.com/assets/9297457/14983676/b2ec03b2-110c-11e6-8791-a9242c240fdc.png">

If a user leaves then I delete that featExtractor from the map:
<img width="670" alt="screen shot 2016-05-02 at 5 14 42 pm" src="https://cloud.githubusercontent.com/assets/9297457/14983702/d1d9e4ec-110c-11e6-9f4f-739f87241d96.png">

I then load the joints into the featExtractor. However when there are two skeletons the application always crashes. Im using ofxOpenNi and for me it crashes on xnWaitAndUpdateData.
<img width="667" alt="screen shot 2016-05-03 at 8 58 55 am" src="https://cloud.githubusercontent.com/assets/9297457/14983790/4ca44f64-110d-11e6-8d3b-6b620300a063.png">

When I dont load the joints into featExtractor in this line: featExtractors[userId].update(joints), ofxOpenNi is successfully tracking two skeletons. If I comment out that line nothing crashes, so the error is with how to load data into the featExtractor for two skeletons together. 

If you have an example of how to do it it would help me a lot!!

**Comment by asarasua** [comment]
Sorry about taking so long to reply, I've been pretty busy with other stuff.

When you say "I set it up in the update loop" is that really the case? Setup should be done in the setup method, not on update.

Also, can you try doing explicit types declaration for the map in your header file? So instead of `map featExtractors;` doing `map<int, ofxKinectFeatures> featExtractors;`

**Comment by danaavesar** [comment]
Thanks for responding!  I actually just reverted to declaring three
separate featExtractor variables instead of the map<>, and it works. I
think I just don't understand C++ and how to use the map function.

On another note, I wanted to ask you about the y position value of the
skeleton. I am getting the position of the torso using kinect.
worldToProjective(featExtractor1.getPosition(torso)), and notice that the y
value increases as I move towards the kinect and decreases I move away
(this is supposed to happen only with the Z direction). It also increases
and decreases as I kneel or stand like it is supposed to, however the
movement towards the kinect or away from it affects the y value as well. Is
that how it is supposed to be or is there some kind of problem?

_Dana Avesar_

**Comment by danaavesar** [comment]
I have one more question for you..I dont know if this is happening to anyone else but I am using ofxOpenNi + this addon and the app always crashes when the skeleton gets too close to the kinect. It crashes on this line in ofxOpenNi:  xnWaitAndUpdateData(GetHandle()); See the screen shot below. 
<img width="924" alt="screen shot 2016-05-13 at 2 26 07 pm" src="https://cloud.githubusercontent.com/assets/9297457/15257975/0a45f3fe-1917-11e6-88f5-f656b4f2f403.png">

This crash doesn't happen when I am running ofxOpenNi by itself. I think it has to do with this section of the code, when joint information from the skeleton is loaded into featExtractor:
<img width="710" alt="screen shot 2016-05-13 at 2 27 44 pm" src="https://cloud.githubusercontent.com/assets/9297457/15257967/00744cf4-1917-11e6-87cc-c935aaae0707.png">

It seems like maybe when a skeleton suddenly disappears, it is still trying to load information from that skeleton that doesn't exist? Im not sure but I was wondering if anyone has encountered this and knows how to prevent it from crashing like that.

**Comment by danaavesar** [comment]
Hi Alvaro, do you live in New York? I am trying to install my project for a
show that starts on Tuesday and it keeps on crashing when someone gets too
close to the kinect. If you have time to help me debug this problem I would
pay you. Please let me know if this is something you would be interested
in.

Dana

_Dana Avesar_

**Comment by asarasua** [comment]
I would be very interested in doing so but I live in Barcelona and currently visiting California with limited internet access.
I hope I can help some more remotely in the near future.

**Comment by danaavesar** [comment]
Hi Alvaro, are you available today or tomorrow? When will you be available?

_Dana Avesar_

**Comment by danaavesar** [comment]
Alvaro your example for ofxopenni and kinect features also crashes on the
same line xnwaitandupdate..I think it has to do with the hack that you
inserted for waiting for isdataavailable(). I would really appreciate it if
you can help me with this today or tomorrow!!

**Comment by asarasua** [comment]
I'm sorry but the soonest I might be able to find some time would be tomorrow (18) afternoon (CET). I'm in the middle of a San Francisco - BCN trip.
